version: '3.8'
services:
  postgres:
    image: postgres:17
    env_file: 
      - .env.local
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dbtools:
    image: postgres:17
    volumes:
      - ./backups:/backups
      - ./scripts:/scripts
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - tools

volumes:
  postgres_data: